BEGIN TRANSACTION;
create sequence hibernate_sequence start 1 increment 1;
create table association (id int8 not null, abbreviation varchar(255), name varchar(255), primary key (id));
create table association_admins (association_id int8 not null, admins_id int8 not null, primary key (association_id, admins_id));
create table barcode (id int8 not null, code varchar(255), user_id int8, primary key (id));
create table event (id int8 not null, created timestamp, name varchar(255) not null, association_id int8 not null, deleted boolean not null, primary key (id));
create table external_attendee (id int8 not null, entered timestamp, event_id int8 not null, email varchar(255), first_name varchar(255), last_name varchar(255), phone varchar(255), primary key (id));
create table ugent_attendee (id int8 not null, entered timestamp, event_id int8 not null, user_id int8, primary key (id));
create table users (id int8 not null, admin boolean not null, email varchar(255), first_name varchar(255), last_name varchar(255), username varchar(255), primary key (id));
alter table if exists association add constraint UK_j7hdrqw5yvwl5kvra0e8geryq unique (abbreviation);
alter table if exists association add constraint UK_8csqky4snm7llk6xk73rfyrwm unique (name);
create index IDX8o8myvieuquqfs0euxcv7ktm9 on barcode (code);
alter table if exists barcode add constraint UK_8o8myvieuquqfs0euxcv7ktm9 unique (code);
alter table if exists users add constraint UK_r43af9ap4edm43mmtq01oddj6 unique (username);
alter table if exists association_admins add constraint FK30fada0vlmy277ndakx438vhh foreign key (admins_id) references users;
alter table if exists association_admins add constraint FKqk113sicp8qylyc1axmcc77o9 foreign key (association_id) references association;
alter table if exists barcode add constraint FKqo8mwag2ubbivc7b19lgde9bc foreign key (user_id) references users;
alter table if exists event add constraint FKb740jyamf5l2nwqt9yls80s7q foreign key (association_id) references association;
alter table if exists external_attendee add constraint FK_p0lnls3gbk9funklqxhid79ku foreign key (event_id) references event;
alter table if exists ugent_attendee add constraint FK7gce76pg81unkhpugxegx9y40 foreign key (user_id) references users;
alter table if exists ugent_attendee add constraint FK_s1xkui3uxk1oook4saus10ncr foreign key (event_id) references event;
END TRANSACTION;