security:
  cas:
    service:
      base-url: http://local.todo.ugent.be:8080

ugent.ldap:
  url: ldaps://ldaps.ugent.be
  userDn: cn=vek-soccer,ou=applications,dc=UGent,dc=be
  password: PLACEHOLDER

## PostgreSQL
spring:
  datasource:
    url: jdbc:postgresql://localhost/covidscanner
    username: covidscanner
    password: covidscanner