security:
  cas:
    server:
      base-url: https://login.ugent.be
      protocol-version: 2  # has to be explicitly declared (default = 3)
    service:
      base-url: https://wish.wina-gent.be/

ugent.ldap:
  url: ldaps://ldaps.ugent.be

azure.keyvault:
  enabled: true
  uri: https://covid-scanner-kv.vault.azure.net/

## PostgreSQL
spring:
  h2:
    console:
      enabled: false
  datasource:
    url: jdbc:postgresql://covid-scanner-db.postgres.database.azure.com/covidscanner
    username: covidscanner@covid-scanner-db