security:
  cas:
    server:
      base-url: https://login.ugent.be
      protocol-version: 2  # has to be explicitly declared (default = 3)
    service:
      paths:
        logout: /logout
      base-url: https://wish.wina-gent.be/

ugent.ldap:
  url: ldaps://ldaps.ugent.be
  userDn: cn=vek-soccer,ou=applications,dc=UGent,dc=be
  password: PLACEHOLDER

## PostgreSQL
spring:
  h2:
    console:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost/wish
    username: wish